import {
  Activity,
  BarChart,
  BookOpen,
  Boxes,
  Brain,
  CheckCircle,
  Circle,
  Code,
  Cpu,
  Database,
  FileText,
  Filter,
  Flame,
  FunctionSquare,
  GitBranch,
  Globe,
  Keyboard,
  Layers,
  Lightbulb,
  MessageSquare,
  Network,
  Package,
  Plug,
  Rocket,
  Scale,
  ScatterChart,
  Shield,
  Sigma,
  Target,
  Trophy,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "bar-chart": BarChart,
  "book-open": BookOpen,
  boxes: Boxes,
  brain: Brain,
  "check-circle": CheckCircle,
  code: Code,
  cpu: Cpu,
  database: Database,
  "file-text": FileText,
  filter: Filter,
  flame: Flame,
  "function-square": FunctionSquare,
  "git-branch": GitBranch,
  globe: Globe,
  keyboard: Keyboard,
  layers: Layers,
  lightbulb: Lightbulb,
  "message-square": MessageSquare,
  network: Network,
  package: Package,
  plug: Plug,
  rocket: Rocket,
  scale: Scale,
  "scatter-chart": ScatterChart,
  shield: Shield,
  sigma: Sigma,
  target: Target,
  trophy: Trophy,
  wrench: Wrench,
  zap: Zap,
};

export function getNodeIcon(key: string): LucideIcon {
  return ICONS[key] ?? Circle;
}
